### ISSUE TITLE
Two redirection links in Core Libraries documentation not working

### ISSUE THREAD

**Issue by tubi-carrillo** [beefytech/Beef_website#17]
Two links from [beef core libraries overview](https://www.beeflang.org/docs/corlib/#beef-core-libraries-overview). These are not a big deal really, but just in case:

- `Dictionary` returns 404 error because [Beef Corlib docs](https://www.beeflang.org/docs/doxygen/corlib/html/namespace_system_1_1_collections.html) does not have defined documentation for it.
- `Text Encoding` has a forward slash missing after the "`html`" ("`...corlib/htmlclass_system...`")

**Comment by Ivo-Balbaert** [comment]
- Dictionary now points to https://www.beeflang.org/docs/doxygen/corlib/html/namespace_system_1_1_collections.html

- Text Encoding now points to: https://www.beeflang.org/docs/doxygen/corlib/html/class_system_1_1_text_1_1_encoding.html

So I think this issue can be closed.
